version: '3.8'
services:
  postgres:
   image: postgres:latest
   container_name: backend-interview-db
   ports:
    - 5432:5432
   volumes:
    - postgres:/var/lib/postgresql/data
   environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DATABASE=${POSTGRES_DATABASE}
volumes:
  postgres:
   name: backend-interview-db